//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuttingMrpDashSvc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Private$\\cuttingMrp1")]
        public string mrpQueue {
            get {
                return ((string)(this["mrpQueue"]));
            }
            set {
                this["mrpQueue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0 50 6 * * ? *")]
        public string stockSumDashCron {
            get {
                return ((string)(this["stockSumDashCron"]));
            }
            set {
                this["stockSumDashCron"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*/2 * * * * ? *")]
        public string autoStockCron {
            get {
                return ((string)(this["autoStockCron"]));
            }
            set {
                this["autoStockCron"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Charlot-PC\\MSSQLSERVER20082;Initial Catalog=CuttingMrp;Persist Securi" +
            "ty Info=True;User ID=sa;Password=123456@")]
        public string db {
            get {
                return ((string)(this["db"]));
            }
            set {
                this["db"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\CHARLOT-PC\\IFShare\\Publish\\cutting")]
        public string autoStockFilePath {
            get {
                return ((string)(this["autoStockFilePath"]));
            }
            set {
                this["autoStockFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0 */7 * * * ? *")]
        public string backFlashCron {
            get {
                return ((string)(this["backFlashCron"]));
            }
            set {
                this["backFlashCron"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WHITEETIHW.csv;BLUEEULB.xlsx")]
        public string autoStockFileRegex {
            get {
                return ((string)(this["autoStockFileRegex"]));
            }
            set {
                this["autoStockFileRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\cz\\MrpDashSvc")]
        public string autoStockCopyFilePath {
            get {
                return ((string)(this["autoStockCopyFilePath"]));
            }
            set {
                this["autoStockCopyFilePath"] = value;
            }
        }
    }
}
