#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuttingMrpBackFlushWPF.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CuttingMrp")]
	public partial class BackFlushDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertBackFlush(BackFlush instance);
    partial void UpdateBackFlush(BackFlush instance);
    partial void DeleteBackFlush(BackFlush instance);
    #endregion
		
		public BackFlushDataContext() : 
				base(global::CuttingMrpBackFlushWPF.Properties.Settings.Default.CuttingMrpConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BackFlushDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BackFlushDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BackFlushDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BackFlushDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BackFlush> BackFlush
		{
			get
			{
				return this.GetTable<BackFlush>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BackFlush")]
	public partial class BackFlush : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _flushId;
		
		private string _partnr;
		
		private string _bomId;

        private System.DateTime _commitTime;

        #region 可扩展性方法定义
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnflushIdChanging(int value);
        partial void OnflushIdChanged();
        partial void OnpartnrChanging(string value);
        partial void OnpartnrChanged();
        partial void OnbomIdChanging(string value);
        partial void OnbomIdChanged();
        partial void OncommitTimeChanging(System.DateTime value);
        partial void OncommitTimeChanged();
        #endregion

        public BackFlush()
		{
			OnCreated();
		}

        public BackFlush(string partNr, string bomId,DateTime nowDateTime)
        {
            this.partnr = partNr;
            this.bomId = bomId;
            this.commitTime = nowDateTime;
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flushId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int flushId
		{
			get
			{
				return this._flushId;
			}
			set
			{
				if ((this._flushId != value))
				{
					this.OnflushIdChanging(value);
					this.SendPropertyChanging();
					this._flushId = value;
					this.SendPropertyChanged("flushId");
					this.OnflushIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partnr", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string partnr
		{
			get
			{
				return this._partnr;
			}
			set
			{
				if ((this._partnr != value))
				{
					this.OnpartnrChanging(value);
					this.SendPropertyChanging();
					this._partnr = value;
					this.SendPropertyChanged("partnr");
					this.OnpartnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bomId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string bomId
		{
			get
			{
				return this._bomId;
			}
			set
			{
				if ((this._bomId != value))
				{
					this.OnbomIdChanging(value);
					this.SendPropertyChanging();
					this._bomId = value;
					this.SendPropertyChanged("bomId");
					this.OnbomIdChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_commitTime", DbType = "DateTime NOT NULL")]
        public System.DateTime commitTime
        {
            
            get
            {
                return this._commitTime;
            }
            set
            {
                if ((this._commitTime != value))
                {
                    this.OncommitTimeChanging(value);
                    this.SendPropertyChanging();
                    this._commitTime = value;
                    this.SendPropertyChanged("commitTime");
                    this.OncommitTimeChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
